name: Salesforce CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install Salesforce CLI (sfdx)
      - name: Install Salesforce CLI
        run: npm install sfdx-cli@latest --global

      # Step 4: Authenticate with Salesforce
      - name: Authenticate with Salesforce Org
        shell: bash
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sfdx force:auth:jwt:grant \
            --client-id ${{ secrets.SF_CONSUMER_KEY1 }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME1 }} \
            --instance-url ${{ secrets.SF_INSTANCE_URL1 }} \
            --setalias ci-org \
            --setdefaultusername

      # Step 5: Verify authentication
      - name: Verify Org Connection
        run: sfdx force:org:display -u ci-org

      # Step 6: Deploy metadata
      - name: Deploy to Salesforce Org
        run: |
          sfdx force:source:deploy \
            -p force-app \
            -u ci-org \
            --testlevel RunLocalTests \
            --json \
            --loglevel fatal
